openapi: 3.0.1
info:
  title: Reindeer API
  version: 0.0.1


tags:
  - name: reindeers
    description: Reindeer api
paths:
  /reindeers:
    get:
      tags:
        - reindeers
      summary: Fetch Reindeer by id
      description: Fetch Reindeer by id
      operationId: fetchReindeerById
      parameters:
        - name: id
          in: query
          description: id of the reindeer
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reindeer'
        404:
          description: Not found
          content: {}
components:
  schemas:
    Reindeer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        title:
          type: string
